<a href="https://colab.research.google.com/github/vishal-achhu/DHV/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [17]:
import numpy as np


array_1d = np.array([1, 2, 3, 4, 5])



print(array_1d.shape)
print(array_1d.size)
print(array_1d.ndim)
print(len(array_1d))



array_2d = np.array([[1, 2, 3],
                     [4, 5, 6]])



print(array_2d.shape)
print(array_2d.size)
print(array_2d.ndim)
print(len(array_2d))



array_3d = np.array([[[1, 2, 3],
                      [4, 5, 6]],

                     [[7, 8, 9],
                      [10, 11, 12]]])



print(array_3d.shape)
print(array_3d.size)
print(array_3d.ndim)
print(len(array_3d))


(5,)
5
1
5
(2, 3)
6
2
2
(2, 2, 3)
12
3
2


In [19]:
a_example = np.arange(1, 10, 2)
print(a_example)


randint_example = np.random.randint(1, 100, size=(3, 3))
print(randint_example)


rand_example = np.random.rand(2, 3)
print(rand_example)


lspace_example = np.linspace(1, 10, num=5)
print(lspace_example)


ones_example = np.ones((2, 3))
print(ones_example)


zeros_example = np.zeros((3, 2))
print(zeros_example)


diag_example = np.diag([1, 2, 3])
print(diag_example)


[1 3 5 7 9]
[[45 55 22]
 [46 70 59]
 [34 19 65]]
[[6.64655457e-04 8.08034122e-01 6.19822466e-01]
 [9.58081797e-01 7.06498791e-01 4.28310287e-02]]
[ 1.    3.25  5.5   7.75 10.  ]
[[1. 1. 1.]
 [1. 1. 1.]]
[[0. 0.]
 [0. 0.]
 [0. 0.]]
[[1 0 0]
 [0 2 0]
 [0 0 3]]


In [22]:
marks= np.random.randint(0, 101, size=10)
print(marks)

[49 86  7 99 44 24 65 35 34  4]


In [24]:
f_marks= marks[marks < 30]
print(f_marks)

[ 7 24  4]


In [25]:
pmarks=marks[marks>=30]
print(pmarks)

[49 86 99 44 65 35 34]


In [27]:
rand2d=([np.random.ranint(0,50,size=5)],[np.random.ranint(0,50,size=5)])

AttributeError: module 'numpy.random' has no attribute 'ranint'

In [28]:
rows = 3
cols = 4
random_2d_array = np.random.rand(rows, cols)
print(random_2d_array)

[[0.36050331 0.67434317 0.93358924 0.53427294]
 [0.178961   0.32138254 0.33520617 0.90115123]
 [0.49950215 0.0777074  0.43575155 0.37651433]]
